import { playerInfo } from "../interface/interface";

export const playersInfo = [
  {
    id: 3173,
    name: "Марк-Андре́",
    lastname: "тер Сте́ген",
    number: 1,
    bearthDate: "30.04.1992",
    img: "/players/Stegen.png",
    country: "Германия",
    countryFlag: "https://flagcdn.com/20x15/de.png",
    teams: [
      { team: "Боруссия (Мёнхенг.)", years: "2009-2014" },
      { team: "Барселона", years: "2014-н/в" },
    ],
    height: 187,
    weight: 85,
    allAppearance: 394,
    cleanSheets: 164,
    saves: 907,
  },
  {
    id: 180898,
    name: "Игна́сио",
    lastname: "Пе́нья",
    number: 13,
    bearthDate: "02.03.1999",
    img: "/players/pena.png",
    country: "Испания",
    countryFlag: "https://flagcdn.com/20x15/es.png",
    teams: [{ team: "Барселона", years: "2018-н/в" }],
    height: 184,
    weight: 78,
    allAppearance: 8,
    cleanSheets: 2,
    saves: 14,
  },
  {
    id: 2000,
    name: "Жоао",
    lastname: "Канселу",
    number: 2,
    bearthDate: "27.05.1994",
    img: "/players/cancelo.png",
    country: "Португалия",
    countryFlag: "https://flagcdn.com/20x15/pt.png",
    teams: [
      { team: "Бенфика", years: "2012-2015" },
      { team: "Валенсия", years: "2015-2018" },
      { team: "Ювентус", years: "2018-2019" },
      { team: "Манчестер Сити", years: "2019-н/в" },
    ],
    height: 182,
    weight: 74,
    allAppearance: 17,
    goals: 3,
    assist: 2,
  },
  {
    id: 3195,
    name: "Маркос",
    lastname: "Алонсо",
    number: 17,
    bearthDate: "28.12.1990",
    img: "/players/Alonso.png",
    country: "Испания",
    countryFlag: "https://flagcdn.com/20x15/es.png",
    teams: [
      { team: "Болтон", years: "2010—2013" },
      { team: "Фиорентина", years: "2013—2016" },
      { team: "Челси", years: "2016—2022" },
      { team: "Барселона", years: "2022-н/в" },
    ],
    height: 188,
    weight: 84,
    allAppearance: 44,
    goals: 3,
    assist: 0,
  },
  {
    id: 3455,
    name: "Андреас",
    lastname: "Кристенсен",
    number: 15,
    bearthDate: "10.04.1996 ",
    img: "/players/Christensen.png",
    country: "Дания",
    countryFlag: "https://flagcdn.com/20x15/dk.png",
    teams: [
      { team: "Челси", years: "2014—2022" },
      { team: "Барселона", years: "2022-н/в" },
    ],
    height: 187,
    weight: 82,
    allAppearance: 47,
    goals: 1,
    assist: 2,
  },
  {
    id: 8499,
    name: "Жюль",
    lastname: "Кунде",
    number: 23,
    bearthDate: "12.11.1998 ",
    img: "/players/Kounde.png",
    country: "Франция",
    countryFlag: "https://flagcdn.com/20x15/fr.png",
    teams: [
      { team: "Бордо", years: "2016—2019" },
      { team: "Севилья", years: "2019—2022" },
      { team: "Барселона", years: "2022-н/в" },
    ],
    height: 180,
    weight: 75,
    allAppearance: 55,
    goals: 2,
    assist: 7,
  },
  {
    id: 15865,
    name: "Серхи",
    lastname: "Роберто",
    number: 20,
    bearthDate: " 07.02.1992",
    img: "/players/Roberto.png",
    country: "Испания",
    countryFlag: "https://flagcdn.com/20x15/es.png",
    teams: [{ team: "Барселона", years: "2010-н/в" }],
    height: 178,
    weight: 68,
    allAppearance: 355,
    goals: 17,
    assist: 40,
  },
  {
    id: 28292,
    name: "Рональд",
    lastname: "Араухо",
    number: 4,
    bearthDate: "07.03.1999",
    img: "/players/arauho.png",
    country: "Уругвай",
    countryFlag: "https://flagcdn.com/20x15/uy.png",
    teams: [
      { team: "Рентистас", years: "2016-2017" },
      { team: "Бостон Ривер", years: "2017-2018" },
      { team: "Барселона", years: "2018-н/в" },
    ],
    height: 188,
    weight: 79,
    allAppearance: 126,
    goals: 8,
    assist: 3,
  },
  {
    id: 32588,
    name: "Иньиго",
    lastname: "Мартинес",
    number: 5,
    bearthDate: "17.05.1991",
    img: "/players/martinez.png",
    country: "Испания",
    countryFlag: "https://flagcdn.com/20x15/es.png",
    teams: [
      { team: "Реал Сосьедад", years: "2009-2018" },
      { team: "Атлетик Бильбао", years: "2018-2023" },
      { team: "Барселона", years: "2023-н/в" },
    ],
    height: 182,
    weight: 76,
    allAppearance: 10,
    goals: 0,
    assist: 0,
  },
  {
    id: 37428,
    name: "",
    lastname: "Рафинья",
    number: 11,
    bearthDate: "14.12.1996",
    img: "/players/raphina.png",
    country: "Бразилия",
    countryFlag: "https://flagcdn.com/20x15/br.png",
    teams: [
      { team: "Витория Гимарайнш", years: "2016-2018" },
      { team: "Спортинг (Лиссабон)", years: "2018-2019" },
      { team: "Ренн", years: "2019-2020" },
      { team: "Лидс Юнайтед", years: "2020-2022" },
      { team: "Барселона", years: "2022-н/в" },
    ],
    height: 176,
    weight: 68,
    allAppearance: 64,
    goals: 12,
    assist: 15,
  },
  {
    id: 172761,
    name: "Алехандро",
    lastname: "Бальде",
    number: 3,
    bearthDate: "18.10.2003",
    img: "/players/balde.png",
    country: "Испания",
    countryFlag: "https://flagcdn.com/20x15/es.png",
    teams: [{ team: "Барселона", years: "2021-н/в" }],
    height: 175,
    weight: 69,
    allAppearance: 70,
    goals: 1,
    assist: 7,
  },
  {
    id: 3182,
    name: "Илкай",
    lastname: "Гюндоган ",
    number: 22,
    bearthDate: "24.10.1990",
    img: "/players/Gundogan.png",
    country: "Германия",
    countryFlag: "https://flagcdn.com/20x15/de.png",
    teams: [
      { team: "Нюрнберг", years: "2009-2011" },
      { team: " Боруссия (Дортмунд)", years: "2011-2016" },
      { team: " Манчестер Сити", years: "2016-2023" },
      { team: "Барселона", years: "2023-н/в" },
    ],
    height: 180,
    weight: 80,
    allAppearance: 20,
    goals: 1,
    assist: 5,
  },
  {
    id: 7559,
    name: "Френки",
    lastname: "Де Йонг",
    number: 21,
    bearthDate: "12.05.1997",
    img: "/players/Frenkie.png",
    country: "Нидерланды",
    countryFlag: "https://flagcdn.com/20x15/nl.png",
    teams: [
      { team: "Аякс", years: "2015-2019" },
      { team: "Барселона", years: "2019-н/в" },
    ],
    height: 181,
    weight: 74,
    allAppearance: 193,
    goals: 16,
    assist: 19,
  },
  {
    id: 8091,
    name: "Ориоль",
    lastname: "Ромеу",
    number: 18,
    bearthDate: "24.09.1991",
    img: "/players/icon.png",
    country: "Испания",
    countryFlag: "https://flagcdn.com/20x15/es.png",
    teams: [
      { team: "Челси", years: "2011-2015" },
      { team: "Саутгемптон", years: "2015-2022" },
      { team: "Жирона", years: "2022-2023" },
      { team: "Барселона", years: "2023-н/в" },
    ],
    height: 183,
    weight: 83,
    allAppearance: 19,
    goals: 0,
    assist: 1,
  },
  {
    id: 171992,
    name: "",
    lastname: "Гави",
    number: 6,
    bearthDate: "05.08.2004",
    img: "/players/gavi.png",
    country: "Испания",
    countryFlag: "https://flagcdn.com/20x15/es.png",
    teams: [{ team: "Барселона", years: "2021-н/в" }],
    height: 173,
    weight: 70,
    allAppearance: 111,
    goals: 7,
    assist: 12,
  },
  {
    id: 371,
    name: "Роберт",
    lastname: "Левандовски",
    number: 9,
    bearthDate: "21.08.1988",
    img: "/players/lewandovski.webp",
    country: "Польша",
    countryFlag: "https://flagcdn.com/20x15/pl.png",
    teams: [
      { team: "Легия II", years: "2005-2006" },
      { team: "Знич", years: "2006-2008" },
      { team: "Лех", years: "2008-2010" },
      { team: "Боруссия (Д)", years: "2010-2014" },
      { team: "Бавария", years: "2014-2022" },
      { team: "Барселона", years: "2022-н/в" },
    ],
    height: 185,
    weight: 81,
    allAppearance: 63,
    goals: 41,
    assist: 12,
  },
  {
    id: 33154,
    name: "Ферран",
    lastname: "Торрес",
    number: 7,
    bearthDate: "29.02.2000",
    img: "/players/torres.webp",
    country: "Испания",
    countryFlag: "https://flagcdn.com/20x15/es.png",
    teams: [
      { team: "Валенсия", years: "2016-2020" },
      { team: "Манчестер Сити", years: "2020-2022" },
      { team: "Барселона", years: "2022-н/в" },
    ],
    height: 184,
    weight: 77,
    allAppearance: 90,
    goals: 19,
    assist: 10,
  },
  {
    id: 39265,
    name: "Жоау",
    lastname: "Феликс",
    number: 14,
    bearthDate: "10.11.1999",
    img: "/players/felix.png",
    country: "Португалия",
    countryFlag: "https://flagcdn.com/20x15/pt.png",
    teams: [
      { team: "Бенфика", years: "2016-2019" },
      { team: "Атлетико Мадрид", years: "2019-2023" },
      { team: "Барселона", years: "2023-н/в" },
    ],
    height: 181,
    weight: 70,
    allAppearance: 17,
    goals: 5,
    assist: 3,
  },
  {
    id: 133860,
    name: "",
    lastname: "Педри",
    number: 8,
    bearthDate: "25.11.2002",
    img: "/players/pedri.png",
    country: "Испания",
    countryFlag: "https://flagcdn.com/20x15/es.png",
    teams: [
      { team: "Лас-Пальмас", years: "2019-2020" },
      { team: "Барселона", years: "2022-н/в" },
    ],
    height: 174,
    weight: 60,
    allAppearance: 117,
    goals: 17,
    assist: 9,
  },
  {
    id: 202283,
    name: "Ламин",
    lastname: "Ямаль",
    number: 27,
    bearthDate: "13.07.2007",
    img: "/players/icon.png",
    country: "Испания",
    countryFlag: "https://flagcdn.com/20x15/es.png",
    teams: [{ team: "Барселона", years: "2023-н/в" }],
    height: 180,
    weight: 65,
    allAppearance: 20,
    goals: 1,
    assist: 1,
  },
  {
    id: 214533,
    name: "Фермин",
    lastname: "Лопес",
    number: 32,
    bearthDate: "11.05.2003",
    img: "/players/fermin.png",
    country: "Испания",
    countryFlag: "https://flagcdn.com/20x15/es.png",
    teams: [{ team: "Барселона", years: "2023-н/в" }],
    height: 174,
    weight: 64,
    allAppearance: 15,
    goals: 2,
    assist: 1,
  },
];
